[package]
name = "ord-set-vec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter-set = "2.0.1"
serde = {version = "1.0.125", features = ["derive"]}
thiserror = "1"